SET @year = YEAR(NOW());

SELECT DAYOFMONTH(LAST_DAY(CONCAT(@year,"-01-15"))), MONTHNAME(CONCAT(@year,"-01-15"))
UNION
SELECT DAYOFMONTH(LAST_DAY(CONCAT(@year,"-02-15"))), MONTHNAME(CONCAT(@year,"-02-15"))
UNION
SELECT DAYOFMONTH(LAST_DAY(CONCAT(@year,"-03-15"))), MONTHNAME(CONCAT(@year,"-03-15"))
UNION
SELECT DAYOFMONTH(LAST_DAY(CONCAT(@year,"-04-15"))), MONTHNAME(CONCAT(@year,"-04-15"))
UNION
SELECT DAYOFMONTH(LAST_DAY(CONCAT(@year,"-05-15"))), MONTHNAME(CONCAT(@year,"-05-15"))
UNION
SELECT DAYOFMONTH(LAST_DAY(CONCAT(@year,"-06-15"))), MONTHNAME(CONCAT(@year,"-06-15"))
UNION
SELECT DAYOFMONTH(LAST_DAY(CONCAT(@year,"-07-15"))), MONTHNAME(CONCAT(@year,"-07-15"))
UNION
SELECT DAYOFMONTH(LAST_DAY(CONCAT(@year,"-08-15"))), MONTHNAME(CONCAT(@year,"-08-15"))
UNION
SELECT DAYOFMONTH(LAST_DAY(CONCAT(@year,"-09-15"))), MONTHNAME(CONCAT(@year,"-09-15"))
UNION
SELECT DAYOFMONTH(LAST_DAY(CONCAT(@year,"-10-15"))), MONTHNAME(CONCAT(@year,"-10-15"))
UNION
SELECT DAYOFMONTH(LAST_DAY(CONCAT(@year,"-11-15"))), MONTHNAME(CONCAT(@year,"-11-15"))
UNION
SELECT DAYOFMONTH(LAST_DAY(CONCAT(@year,"-12-15"))), MONTHNAME(CONCAT(@year,"-12-15"))

